##!
# Reports information about the CMake and sets compiler general
# options depending on the selected compiler.
#
if ("${CMAKE_PROJECT_NAME}" STREQUAL "${PROJECT_NAME}")
	list(APPEND CMAKE_MESSAGE_INDENT "CMake ")
	message(STATUS "Version: ${CMAKE_VERSION}")
	message(STATUS "Message Log Level : ${CMAKE_MESSAGE_LOG_LEVEL}")
	message(STATUS "Verbose Makefile  : ${CMAKE_VERBOSE_MAKEFILE}")
	message(STATUS "Build Type        : ${CMAKE_BUILD_TYPE}")
	message(STATUS "Generator         : ${CMAKE_MAKE_PROGRAM}")
	message(STATUS "System            : ${CMAKE_SYSTEM}")
	message(STATUS "Host System       : ${CMAKE_HOST_SYSTEM}")
	message(STATUS "Cross Compiling   : ${CMAKE_CROSSCOMPILING}")
	message(STATUS "System Info File  : ${CMAKE_SYSTEM_INFO_FILE}")
	message(STATUS "System Processor  : ${CMAKE_SYSTEM_PROCESSOR}")
	message(STATUS "Runtime Output Dir: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
	message(STATUS "Library Output Dir: ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
	# Make the target property 'CXX_STANDARD' a requirement.
	set(CMAKE_CXX_STANDARD_REQUIRED ON)
	# Report when the global C++ standard has not been set.
	if ("${CMAKE_CXX_STANDARD}" STREQUAL "")
		message(SEND_ERROR "Global C++ standard using 'CMAKE_CXX_STANDARD' has not been set!")
	endif ()
	message(STATUS "C   Launcher: ${CMAKE_C_COMPILER_LAUNCHER}")
	message(STATUS "C++ Launcher: ${CMAKE_CXX_COMPILER_LAUNCHER}")
	message(STATUS "C   Compiler: ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION} ${CMAKE_C_COMPILER}")
	message(STATUS "C++ Compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} ${CMAKE_CXX_COMPILER}")
	message(STATUS "RC  Compiler: ${CMAKE_RC_COMPILER}")
	message(STATUS "RanLib      : ${CMAKE_RANLIB}")
	message(STATUS "Nm          : ${CMAKE_NM}")
	message(STATUS "Ar          : ${CMAKE_AR}")
	message(STATUS "Linker      : ${CMAKE_LINKER}")
	message(STATUS "Strip       : ${CMAKE_STRIP}")
	# Remove the indentation of the message() function.
	list(POP_BACK CMAKE_MESSAGE_INDENT)
	# Add Scanframe indents.
	list(APPEND CMAKE_MESSAGE_INDENT "Sf ")
	message(STATUS "Running in Docker: ${SF_DOCKER}")
	message(STATUS "Host Architecture: ${SF_HOST_ARCHITECTURE}")
	message(STATUS "Architecture     : ${SF_ARCHITECTURE}")
	message(STATUS "Compiler         : ${SF_COMPILER}")
	message(STATUS "Cross Compiling  : ${SF_CROSSCOMPILING}")
	message(STATUS "Build Testing    : ${SF_BUILD_TESTING}")
	message(STATUS "Build QT         : ${SF_BUILD_QT}")
	message(STATUS "Coverage Targets : ${SF_COVERAGE_ONLY_TARGETS}")
	# Remove the indentation of the message() function.
	list(POP_BACK CMAKE_MESSAGE_INDENT)
	list(APPEND CMAKE_MESSAGE_INDENT "Env ")
	set(_Vars "SF_EXECUTABLE_DIR;SF_LIBRARY_DIR")
	if (NOT WIN32)
		list(APPEND _Vars "LD_LIBRARY_PATH")
	else ()
		list(APPEND _Vars "PATH")
	endif ()
	foreach (_Var IN LISTS _Vars)
		if (_Var MATCHES "PATH$")
			Sf_ListPath("$ENV{${_Var}}" "${_Var}")
		else ()
			message(STATUS "${_Var}: $ENV{${_Var}}")
		endif ()
	endforeach ()
	list(POP_BACK CMAKE_MESSAGE_INDENT)
endif ()

