include("${CMAKE_CURRENT_LIST_DIR}/SfQtLibraryCommon.cmake")

Sf_QtLibraryDownload("${SfQtLibrary_VERSION}")

# When the Qt version directory was found/installed set the cmake prefix path.
if (NOT "$ENV{QT_VER_DIR}" STREQUAL "")
	if (SF_COMPILER STREQUAL "gnu" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
		set(_QtCompileName "gcc_64")
	elseif (SF_COMPILER STREQUAL "ga" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
		set(_QtCompileName "gcc_64")
	elseif (SF_COMPILER STREQUAL "mingw" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
		set(_QtCompileName "mingw_64")
	elseif (SF_COMPILER STREQUAL "gw" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
		set(_QtCompileName "mingw_64")
		# The QT_HOST_PATH is required since for when cross compiling from Linux.
		if (NOT DEFINED QT_HOST_PATH AND NOT DEFINED ENV{QT_HOST_PATH})
			string(REPLACE "/win-x86_64/" "/lnx-x86_64/" QT_HOST_PATH "$ENV{QT_VER_DIR}/gcc_64")
			if (NOT EXISTS "${QT_HOST_PATH}")
				message(FATAL_ERROR "Required QT_HOST_PATH '${QT_HOST_PATH}' was not found!")
			endif ()
		endif ()
	elseif (SF_COMPILER STREQUAL "msvc" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
		set(_QtCompileName "msvc2019_64")
	else ()
		message(FATAL_ERROR "SF_COMPILER '${SF_COMPILER}' has no solution for the 'CMAKE_PREFIX_PATH' path!")
	endif ()
	set(_QtVerCompiler "$ENV{QT_VER_DIR}/${_QtCompileName}")
	if (EXISTS "${_QtVerCompiler}/lib/cmake")
		# Add the cmake directory to the cmake search path.
		list(PREPEND CMAKE_PREFIX_PATH "${_QtVerCompiler}/lib/cmake")
		# Set the Qt include directory.
		set(SF_QT_INCLUDE_DIRECTORY "${_QtVerCompiler}/include")
	else ()
		message(FATAL_ERROR "Compiler '${SF_COMPILER}' QT cmake library prefix directory '${_QtVerCompiler}/lib/cmake' does not exist!")
	endif ()
	unset(_QtCompileName)
endif ()
