[OPTIONS]
debug-level=0

; Resolves installed WinGet packages by PackageIdentifier and sets environment variables
; to the package's InstallLocation.
[DEPENDENCY@]
SF_QT_RT=Scanframe.sf-qt-rt-@SF_QT_VERSION@

; Environment entries section replacing or adding variables.
[ENV@]
PATH=%SF_QT_RT%\Scanframe\qt\@SF_QT_VERSION@\@SF_COMPILER_SUBDIR@\bin;%PATH%

; Application run section where relative directories and the executable
; are resolved as relative to the `cmd-pass.exe` realpath.
[RUN@]
console=@SF_WINLAUNCH_CONSOLE@
;workdir=.
executable=@SF_WINLAUNCH_EXECUTABLE@
