[OPTIONS]
debug-level=0

[ENV@]
; Test for using wine.
;PATH=Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix;Z:\usr\x86_64-w64-mingw32\lib;Z:\mnt\server\userdata\applications\library\qt\win-x86_64\6.10.1\mingw_64\bin;%PATH%
PATH=%USERPROFILE%\AppData\Local\Microsoft\WinGet\Packages\@SF_PROVIDER_NAME@.sf-qt-rt-@SF_QT_VERSION@_@SF_WINGET_SOURCE_IDENTIFIER@@SF_WINGET_GROUP@\@SF_PROVIDER_NAME@\qt\@SF_QT_VERSION@\@SF_COMPILER_SUBDIR@\bin;%PATH%

[RUN@]
console=@SF_WINLAUNCH_CONSOLE@
;workdir=.
executable=@SF_WINLAUNCH_EXECUTABLE@
