# See: https://cmake.org/cmake/help/latest/cpack_gen/deb.html
set(CPACK_DEBIAN_PACKAGE_DEBUG OFF)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEB_COMPONENT_INSTALL ON)

# Variable CPACK_DEBIAN_PACKAGE_VERSION defaults to the CPACK_PACKAGE_VERSION so no need to set it.
#set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
# Variable CPACK_DEBIAN_PACKAGE_RELEASE is not used and resolved using CPACK_PACKAGE_VERSION.
#set(CPACK_DEBIAN_PACKAGE_RELEASE "")

# Set the architecture conform the compiler.
# To check the resulting package architecture use:
#    dpkg-deb -f <deb-file> architecture
if (SF_ARCHITECTURE STREQUAL "x86_64")
	# Set the architecture name used by debian.
	set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
	set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS OFF)
# Check for the aarch64.
elseif (SF_ARCHITECTURE STREQUAL "x86")
	set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
	set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS OFF)
elseif (SF_ARCHITECTURE STREQUAL "aarch64")
	set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "arm64")
	set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS OFF)
elseif (SF_ARCHITECTURE STREQUAL "arm")
	set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "armhf")
	set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS OFF)
else ()
	message(SEND_ERROR "Architecture '${SF_ARCHITECTURE}' not supported!")
endif ()

# Set the compression type and level.
set(CPACK_DEBIAN_COMPRESSION_TYPE gzip)
set(CPACK_DEBIAN_COMPRESSION_LEVEL 9)

set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS OFF)
#set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "${CMAKE_PROJECT_HOMEPAGE_URL}")
