# See: https://cmake.org/cmake/help/latest/cpack_gen/nsis.html
# The NSIS does not use the CPACK_NSIS_PACKAGE_NAME as a filename but only CPACK_PACKAGE_FILE_NAME.

set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_LIST_DIR}/res/logo.ico")
set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_LIST_DIR}/res/logo.ico")
set(CPACK_NSIS_PACKAGE_NAME "${SF_PACKAGE_BASE_NAME}-${SF_ARCHITECTURE_SAFE}_${SF_GIT_TAG_VERSION}-${SF_PACKAGE_RELEASE}")
set(CPACK_NSIS_DISPLAY_NAME "${SF_PACKAGE_BASE_NAME} - ${SF_ARCHITECTURE}")
set(CPACK_NSIS_URL_INFO_ABOUT "${CMAKE_PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_HELP_LINK "${CMAKE_PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_CONTACT "${CPACK_PACKAGE_CONTACT}")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_IGNORE_LICENSE_PAGE ON)
set(CPACK_NSIS_INSTALLER_NAME "${SF_PACKAGE_BASE_NAME}")
# Executable installer name without extension.
set(CPACK_PACKAGE_FILE_NAME "${CPACK_NSIS_PACKAGE_NAME}")


