; File for adding environment during the nested calls of the script.

[config]
; File for running an executable with the cmake environment.
cmake-run-file=cmake/lib/run-executable.cmake
; Override the default docker image using a smaller one without the QT libraries.
;docker-image=nexus.scanframe.com/amd64/gnu-cpp:24.04
;docker-image=avolphen/amd64-gnu-cpp:24.04
;docker-image=amd64/gnu-cpp:24.04

; Sematic versioning type impact map.
[config-ver-type-map]
fix=patch,Bugfix
feat=minor,Feature
build=patch,Build Tool/Process
chore=patch,Chore
ci=patch,CI Configuration
docs=patch,Documentation
style=patch,Code Formatting/Styling
refactor=patch,Code Refactoring
perf=patch,Performance
test=none,Test Addition/Modification
revert=patch,Revert of Commit

; Section for optional include file which is merged.
[__include__]
user=user.ini

; Pulse audio server config. Need volume mapping from host.
[pulse-audio]
# Location for the pulse audio server to find the users socket (check with: pactl info).
PULSE_SERVER=unix:/run/user/${UID}/pulse/native
# To get the Qt theme as on the host.
QT_QPA_PLATFORMTHEME=xdgdesktopportal
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${UID}/bus

[qt-ver]
RUN_QT_VER=6.10.1

; Environment added when running in Wine natively.
; It needs Python 3.12, CMake 4.2, Ninja 1.13 and NSIS 3.11 which can be installed but also shared through the toolchain directory.
; Windows Git is not completely working since it is using Cygwin libraries and a Git server/client is devised to overcome it.
[env.wine@]
; Convenient variable for common base directory.
TOOL_ROOT=Z:${RUN_DIR}\lib\toolchain\win-x86_64-cmake-4.2-combi
; Configuration for tools as cmake, git and ninja for within the Wine environment.
WINEPATH=${TOOL_ROOT}\cmake\bin;${TOOL_ROOT}\bin;${TOOL_ROOT}\python;${TOOL_ROOT}\nsis
; Alternate port for the git server incase of conflicts.
;GIT_SERVER_PORT=8888
; Alternate Wine prefix directory.
;WINEPREFIX=

; Environment added before running Docker.
[env.docker@]
; Nothing yet.

; Environment added before running with the compiler msvc natively.
[env.msvc@]
__inherit__=qt-ver
SF_EXEC_DIR_SUFFIX=-msvc
; Location of the root of the MSVC toolchain in the Wine environment.
; The rest is environment as below is configured in the file CMakePresets.json to allow multiple compilers to be configured in the same project.
MSVC_ROOT=${RUN_DIR}\lib\toolchain\w64-x86_64-msvc-2022
; Overrides QT_VER_DIR for subcommand 'run'.
RUN_QT_VER_DIR=${RUN_DIR}\lib\qt\w64-x86_64\${RUN_QT_VER}
; Even though this variable is not used by Windows it is used to locate the DLL's for running the application.
LD_LIBRARY_PATH=${RUN_QT_VER_DIR}\msvc_64\bin
PATH=${LD_LIBRARY_PATH};${PATH}
WINEDEBUG=fixme-all

; Environment added before running with the compiler msvc in Wine.
[env.msvc.wine@]
__inherit__=env.msvc@

; Environment added before running Wine in the Docker container.
[env.wine.docker@]
__inherit__=qt-ver,pulse-audio
; Overrides QT_VER_DIR for subcommand 'run'.
RUN_QT_VER_DIR=Z:\home\${USER}\lib\qt\w64-x86_64\${RUN_QT_VER}

; Environment added before running with the compiler msvc in Wine in the Docker container.
[env.msvc.wine.docker@]
__inherit__=qt-ver
# The Docker container is build with the MSVC toolchain. (fuse-zip mounted in the home directory).
MSVC_ROOT=Z:\home\${USER}\toolchain\w64-x86_64-msvc-2022
SF_EXEC_DIR_SUFFIX=-msvc
RUN_QT_VER_DIR=Z:\home\${USER}\lib\qt\w64-x86_64\${RUN_QT_VER}
PATH=${RUN_QT_VER_DIR}\msvc_64\bin;${PATH}

; Environment added before running the 'gnu' compiler natively.
[env.gnu@]
__inherit__=qt-ver
SF_EXEC_DIR_SUFFIX=-gnu
# Normally the RUN_PATH is dealing with this but when compiled differently it must be set.
LD_LIBRARY_PATH=${RUN_DIR}/lib/qt/lnx-x86_64/${RUN_QT_VER}/gcc_64/lib

; Environment added before running the 'gnu' compiler in the Docker container.
[env.gnu.docker@]
__inherit__=qt-ver,pulse-audio
SF_EXEC_DIR_SUFFIX=-gnu
# Normally the RUN_PATH is dealing with this but when compiled differently it must be set.
LD_LIBRARY_PATH=/home/${USER}/lib/qt/lnx-x86_64/${RUN_QT_VER}/gcc_64/lib

; Environment added when running wine natively to execute the Windows cross-compiled targets.
[env.gw@]
__inherit__=qt-ver
SF_EXEC_DIR_SUFFIX=-gw
WINEPATH=Z:\usr\x86_64-w64-mingw32\lib;Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix
; Overrides QT_VER_DIR for subcommand 'run'.
RUN_QT_VER_DIR=${RUN_DIR}/lib/qt/win-x86_64/${RUN_QT_VER}

; Environment added before running the 'mingw' compiler natively.
[env.mingw@]
__inherit__=qt-ver
SF_EXEC_DIR_SUFFIX=-mingw
; Even though this variable is not used by Windows it is used to locate the DLL's for running the application.
LD_LIBRARY_PATH=${RUN_DIR}\lib\toolchain\w64-x86_64-mingw-1320-posix\bin;${RUN_DIR}\lib\qt\w64-x86_64\${RUN_QT_VER}\mingw_64\bin;lib
PATH=${LD_LIBRARY_PATH};${PATH}

[env.mingw.wine@]
__inherit__=env.mingw@

; Environment added before running the 'mingw' compiler in Docker and Wine.
[env.mingw.wine.docker@]
__inherit__=qt-ver
SF_EXEC_DIR_SUFFIX=-mingw
PATH=Z:\home\${USER}\toolchain\w64-x86_64-mingw-1320-posix\bin;Z:\home\${USER}\lib\qt\w64-x86_64\${RUN_QT_VER}\mingw_64\bin;lib;${PATH}

; Environment added before running the 'ga' compiler in Docker.
[env.ga.docker@]
__inherit__=qt-ver,pulse-audio
; Puts the binary in 'bin/lnx64-ga'.
SF_EXEC_DIR_SUFFIX=-ga

; Environment added before running the 'gw' compiler in the Docker container.
[env.gw.docker@]
__inherit__=qt-ver,pulse-audio
SF_EXEC_DIR_SUFFIX=-gw
; Provides compiler std libraries to be found.
WINEPATH=Z:\usr\x86_64-w64-mingw32\lib;Z:\usr\lib\gcc\x86_64-w64-mingw32\13-posix;
; Prevent displaying Wine warnings.
WINEDEBUG=fixme-all
# Optional for allowing the .exe files to be executed from Linux. Required compiler std libraries are also part of the Qt library.
;WINEPATH=Z:\home\${USER}\lib\qt\win-x86_64\${RUN_QT_VER}\mingw_64\bin;lib
; Overrides QT_VER_DIR since Wine does not pass any 'QT_' prefixed variables.
RUN_QT_VER_DIR=/home/${USER}/lib/qt/win-x86_64/${RUN_QT_VER}
